#!/usr/bin/env bash
# script prints the domain and subdomain

print_domain_subdomain() {
    local result=$(dig +short "$1.$2" | awk '{ print $2, $1 }')

    if [ -n "$result" ]; then
        echo "The subdomain $2 is a $result record and points to $result"
    fi
}

if [ "$#" -eq 2 ]; then
    print_domain_subdomain "$1" "$2"
else
    for subdomain in www lb-01 web-01 web-02; do
        print_domain_subdomain "$1" "$subdomain"
    done
fi

