#!/usr/bin/env bash
# Update and install Nginx
sudo apt-get update -y -qq
sudo apt-get install nginx -y

# Start Nginx service
sudo service nginx start

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Create a default index.html file with "Hello World"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx (alternative to systemctl)
sudo kill -HUP $(pgrep nginx) 

