#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

# Update package repositories
sudo apt-get update

# Install Nginx if not installed
if ! command -v nginx &> /dev/null; then
    sudo apt-get install -y nginx
fi

# Create index.html with "Hello World!" if not present
index_file="/var/www/html/index.html"
if [ ! -f "$index_file" ]; then
    echo "Hello World!" | sudo tee "$index_file"
fi

# Define Nginx configuration
new_config="
server {
    listen 80 default_server;
    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
    add_header X-Served-By $(hostname);
    rewrite ^/redirect_me https://youtube.com/watch?v=3j66gHbyFF8 permanent;
}
"

# Update Nginx configuration file
sudo cp /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default.backup
echo "$new_config" | sudo tee /etc/nginx/sites-enabled/default

# Validate Nginx configuration
sudo nginx -t

# Reload Nginx to apply changes
sudo service nginx reload
