#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

# Update package repositories
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create index.html with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Fetch server hostname
server_hostname=$(hostname)

# Define Nginx configuration string with hostname
new_string="server_name $server_hostname;\n\trewrite ^\/redirect_me https:\/\/youtube.com\/watch?v=3j66gHbyFF8 permanent;"

# Update Nginx configuration file with custom string
sudo sed -i "s/server_name _:/$new_string/" /etc/nginx/sites-enabled/default

# Create 404.html with custom message
echo "C'est n'est pas une page" | sudo tee /var/www/html/404.html

# Add custom HTTP header with server hostname
sudo sed -i "/server_name $server_hostname;/a add_header X-Served-By $server_hostname;" /etc/nginx/sites-enabled/default

# Validate Nginx configuration
sudo nginx -t

# Restart Nginx service
sudo service nginx restart
