#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
# Update package lists
sudo apt-get update -y -qq

# Install HAProxy
sudo apt install haproxy -y

# craete a backup of the default server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

# Configure HAProxy
server_config=\ 
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend yellowtech-frontend
    bind *:80
    mode http
    default_backend yelloetech-backend
backend yellowtech-backend
    balance roundrobin
    server 410386-web-01 100.25.222.45:80 check
    server 410386-web-02 54.236.43.107:80 check
"

echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
if [ "$(pgrep -c haproxy)" -le 0 ]; then
        sudo service haproxy start
else
        sudo service haproxy restart

echo "Done with the installation"
