#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

echo "Performing updates and checks..."

function install_package() {
	command -v "$1" &> /dev/null

	if [ $? -ne 0 ]; then
		echo "Installing: $1"
		sudo apt-get update -y -qq && \
			sudo apt-get install -y "$1" -qq
		echo
	else
		echo "${1} is already installed."
	fi
}

echo "Installing HAProxy..."
install_package haproxy

echo "Configuring the Load Balancer..."

# Backup default server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config="
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend yellowtech-frontend
    bind *:80
    default_backend yellowtech-backend

backend yellowtech-backend
    balance roundrobin
    server 151666-web-01 100.25.190.21:80 check
    server 151666-web-02 54.160.77.90:80 check
"

echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

echo "Configured - Roundrobin On web-01 & web-02"

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi
