#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server
# Update package lists

sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<'EOF'
frontend besthor_frontend
    bind *:80
    mode http
    default_backend besthor_backend

backend besthor_backend
    balance roundrobin
    server 176572-web-01 54.165.168.252:80 check
    server 176572-web-02 34.237.91.136:80 check
EOF

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Test the HAProxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the HAProxy service
sudo service haproxy restart
