#!/usr/bin/env bash
# Update and install Nginx
echo "Updating packages..."
sudo apt-get update -y -qq
echo "Installing Nginx..."
sudo apt-get install nginx -y

# Start Nginx service
echo "Starting Nginx service..."
sudo service nginx start

# Allow Nginx through the firewall
echo "Allowing Nginx through the firewall..."
sudo ufw allow 'Nginx HTTP'

# Create a default index.html file with "Hello World"
echo "Creating default index.html file..."
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure Nginx redirection
replacement_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/youtube.com\/watch?v=3j66gHbyFF8 permanent;"
sudo sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-available/default

# Creating the 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_404_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$new_404_string/" /etc/nginx/sites-enabled/default

# Restart Nginx (alternative to systemctl)
echo "Restarting Nginx..."
sudo service nginx restart

echo "Nginx setup completed successfully."
