#!/usr/bin/env bash
# This script displays a list of current running processes
# shows all processes, for all users, including those which might not have a TTY
# shown in a user-oriented format
# Show process hierarchy
ps -auxf
