#!/usr/bin/env bash
# This script displays "Best School" ten times and bad luck at 4th iteration
# and good luck at 8th iteration
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]; then
		echo -e "bad luck"
	elif [ $i -eq 8 ]; then
		echo -e "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
