#!/usr/bin/env bash
# This script displays numbers 1-20 and displays:
# bad luck from China after the 4th iteration
# bad luck from Japand after the 9th iteration
# back luck from Italy after the 17th iteration
i=1
while [ $i -le 20 ]
do
	case $i in
		4)
			echo $i
			echo "bad luck from China"
			;;
		9)
			echo $i
			echo "bad luck from Japan"
			;;
		17)
			echo $i
			echo "bad luck from Italy"
			;;
		*)
			echo $i
			;;
	esac
	i=$((i+1))
done
