#!/usr/bin/env bash
# This script displays the current directory in a list format
# where only the part of the name after the first dash is displayed

for file in *
do
	if [[ ! -f "$file" || "$file" == .* ]]; then
		continue
	fi
	filename=$(basename "$file")
	editted_name="${filename#*-}"
	echo "$editted_name"
done
