#!/usr/bin/env bash
# This script configers an Ubuntu servies with these requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

# create back up file
cp /etc/hosts ~/hosts.new
# change IP addresses in the host file
echo "127.0.0.2          localhost" > ~/hosts.new
echo "8.8.8.8          facebook.com" > ~/hosts.new
cp -f ~/hosts.new /etc/hosts
