#!/usr/bin/env bash
# script that configures a container to meet requirements
# Replace nginx user and group in nginx.config
sed -i 's/user\s*nginx;/user nginx nginx;/g' /etc/nginx/nginx.conf

# Handle listening on all active IPs on port 8080
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default

# restart nginx service
service nginx restart

# Verify nginx process status
ps auxff | grep [n]ginx

# Check if nginx is listening on port 8080
nc -z 0 8080
echo $?
