#!/usr/bin/env bash
# script that configures a container to meet requirements
# Define file paths
NGINX_CONF="/etc/nginx/nginx.conf"
NGINX_DEFAULT_CONF="/etc/nginx/sites-available/default"

# Set Nginx user to nginx in nginx.conf
sed -i "s/#user www-data/user nginx/g" "$NGINX_CONF"

# Change default port from 80 to 8080 in default configuration
sed -i "s/80/8080/g" "$NGINX_DEFAULT_CONF"

# Set permissions for nginx.conf
chmod 644 "$NGINX_CONF"

# Stop Apache2 service
pkill apache2

# Start Nginx service as the nginx user
sudo -u nginx service nginx start
