#!/usr/bin/env bash
# condensed version of task 1
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/sites-available/default
sudo pkill aphache2
sudo -u ngnix service nginx start
